### ISSUE TITLE
Weird layout

### ISSUE THREAD

**Issue by alanzanattadev** [tuomashatakka/reduced-dark-ui#2] opened 2016-12-31 08:54 UTC
Hi,

I am on a Dell XPS 15 with 4K resolution (3860x2160) and the layout seems to not support this high dpi.

I attach you a screenshot to show you the issue

Thank you :)
![screenshot from 2016-12-31 09-51-13](https://cloud.githubusercontent.com/assets/9500204/21576823/07fb97e6-cf3f-11e6-8444-a491180e7f6a.png)

**Comment by tuomashatakka** [comment] 2016-12-31 17:24
Thanks for the feedback.

Looks like there is a problem with tree view's content overflowing when the fixed tab bar and fixed project root are both enabled,  disabling either of them should solve the issue for now. 

I'm currently working on the trew view panel so the fix for this should be soon available.  If you could provide answers to the following questions, it would be helpful.
 - Does the tree view panel display correctly when it's on the right side of the editor? 
 - Does reloading the theme and/or the window help?
 - Is there any tree view related other packages enabled? 
 - Does the problem exist with only one root directory? 
 - Does changing the theme's setting as mentioned above fix the issue? 

And nice to see that people are interested in this package. If you have any ideas or feedback, feel free to ask :)

**Comment by alanzanattadev** [comment] 2016-12-31 17:53
I've tried many settings so this is the entire feedback :

- It's almost the same on the right side
- reloading doesn't help
- no tree-view related packages
- with only one root directory it's waaaaaaaaaaaay better, multi root directories is a mess :D
- Yes, I removed both because one or the other make the design ugly, it's fixed

Also, the UI scaling is so big on my screen, changing UI Scale setting is useless, it doesn't change anything. Please, adapt this for 4K screens :(
Another detail, with reveal-on-hover for notifications and tree-view, we have to mouse the mouse everywhere, please set it as a setting toggable :)

And make the status bar centered, I mean, every components in the status bar are not centered :)

Thank you !

**Comment by tuomashatakka** [comment] 2017-01-02 01:31
That is a good point with notifications and panels needing a constant mouse interaction. I'll make it possible to disable that. I've considered adding a key shortcut for toggling panels - do you think that would be useful? (for example, alt + 1 could toggle the topmost panel and so on)

As for the scaling option, it is currently based on the editor's font size setting, does changing that help (settings - > editor - > font size)? I haven't tested that on default value so it could be the issue. Anyway, I'll take a look into that too :) 

Status bar is also under development, haven't had time to put too much effort into it just yet. 

The tree view is a bit of a problem, haven't found a good solution just yet. For some reason the inner wrapper fails to adapt to the given width with the flexbox applied so the root directory tabs overflow even if the overflowing is set to hidden. With horizontal scrolling it doesn't overflow but it's pretty counter-intuitive. I'll try to figure that one out.

**Comment by alanzanattadev** [comment] 2017-01-02 14:21
The UI doesn't have to reflect fontSize :) though I use small fonts.

But keep going ! :) that's great work

**Comment by tuomashatakka** [comment] 2017-01-06 19:25
Forgot to reference this issue from the latest commit 2b4774f666acdb61d299b8898a009617a447ed10 (styles/tree-view. less and styles/ui-theme-settings.less). I will take a closer look at it when I have more time, but at least it should not overflow anymore.

I also disabled the panel collapsing, will make a setting for it when I have time. 

Status bar and scaling should now work. Please let me know if the layout is better now 🙂

**Comment by alanzanattadev** [comment] 2017-01-06 23:45
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.12.8
**Electron Version**: 1.3.13
**System**: linux 4.8.15
**Thrown From**: [reduced-dark-ui](https://github.com/tuomashatakka/reduced-dark-ui) package, v0.4.0


### Stack Trace

Failed to activate the reduced-dark-ui theme

```
At error evaluating function `mix`: color1.toHSL is not a function in /home/alan/.atom/packages/reduced-dark-ui/styles/ui-variables.less:15:13

LessError: error evaluating function `mix`: color1.toHSL is not a function
  at /home/alan/.atom/packages/reduced-dark-ui/styles/ui-variables.less:15:13
```

### Commands

```
     -0:32.5.0 tree-view:show (atom-workspace.workspace.scrollbars-visible-always.theme-duotone-dark-space-syntax.theme-one-dark-ui)
     -0:29.5.0 command-palette:toggle (atom-text-editor.editor.is-focused)
     -0:28.6.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:28.5.0 application:add-project-folder (atom-text-editor.editor)
     -0:13.5.0 command-palette:toggle (atom-text-editor.editor.is-focused)
     -0:12.2.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:12.2.0 application:add-project-folder (atom-text-editor.editor)
     -0:10.4.0 command-palette:toggle (atom-text-editor.editor.is-focused)
     -0:09.1.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:09.1.0 tree-view:show (atom-text-editor.editor)
     -0:03.6.0 settings-view:open (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "autoHideMenuBar": true,
    "telemetryConsent": "limited",
    "themes": [
      "reduced-dark-ui",
      "duotone-dark-space-syntax"
    ]
  },
  "reduced-dark-ui": {
    "fixedProjectRoot": false,
    "fixedTabBar": false,
    "icons": {
      "Tree View Resizer Tool Panel": {
        "icon": "ios-close-empty",
        "iconset": "ion"
      },
      "tree-view-resizer-tool-panel": {
        "icon": "repo",
        "iconset": "icon"
      }
    },
    "overrideEditorBackground": false,
    "tabSizing": false
  }
}
```

### Installed Packages

```coffee
# User
apex-syntax, v0.1.0 (inactive)
apex-ui, v0.2.1 (inactive)
block-travel, v1.0.5 (active)
dark-monochromatic-syntax, v0.0.0 (inactive)
duotone-dark-sea-syntax, v2.0.1 (inactive)
duotone-dark-space-syntax, v2.0.1 (inactive)
duotone-dark-syntax, v2.0.1 (inactive)
duotone-light-syntax, v2.0.1 (inactive)
fast-import-js, v0.5.1 (active)
file-icons, v2.0.7 (active)
flow-ide, v1.2.4 (active)
gloom, v0.4.0 (inactive)
hyper-ui, v0.1.2 (inactive)
infra-syntax, v0.0.0 (inactive)
language-babel, v2.48.5 (active)
linter, v1.11.18 (active)
nifty-syntax, v0.1.0 (inactive)
reduced-dark-ui, v0.4.0 (inactive)
redux-devtools, v0.5.1 (inactive)
sierra-syntax, v0.1.3 (inactive)
swackets, v0.12.1 (active)
atom-dark-syntax, v0.27.0 (inactive)
atom-dark-ui, v0.52.0 (inactive)
atom-light-syntax, v0.28.0 (inactive)
atom-light-ui, v0.45.0 (inactive)
base16-tomorrow-dark-theme, v1.3.0 (inactive)
base16-tomorrow-light-theme, v1.3.0 (inactive)
one-dark-ui, v1.6.2 (inactive)
one-light-ui, v1.6.2 (inactive)
one-dark-syntax, v1.5.0 (inactive)
one-light-syntax, v1.5.0 (inactive)
solarized-dark-syntax, v1.0.5 (inactive)
solarized-light-syntax, v1.0.5 (inactive)
about, v1.7.0 (active)
archive-view, v0.62.0 (active)
autocomplete-atom-api, v0.10.0 (active)
autocomplete-css, v0.13.1 (active)
autocomplete-html, v0.7.2 (active)
autocomplete-plus, v2.31.4 (active)
autocomplete-snippets, v1.11.0 (active)
autoflow, v0.27.0 (inactive)
autosave, v0.23.1 (active)
background-tips, v0.26.1 (active)
bookmarks, v0.42.0 (active)
bracket-matcher, v0.82.2 (active)
command-palette, v0.39.0 (active)
deprecation-cop, v0.54.1 (active)
dev-live-reload, v0.47.0 (active)
encoding-selector, v0.22.0 (active)
exception-reporting, v0.40.0 (active)
find-and-replace, v0.202.2 (inactive)
fuzzy-finder, v1.4.0 (active)
git-diff, v1.1.0 (active)
go-to-line, v0.31.0 (inactive)
grammar-selector, v0.48.2 (active)
image-view, v0.60.0 (active)
incompatible-packages, v0.26.1 (active)
keybinding-resolver, v0.35.0 (active)
line-ending-selector, v0.5.0 (active)
link, v0.31.2 (inactive)
markdown-preview, v0.158.8 (active)
metrics, v1.1.2 (active)
notifications, v0.65.1 (active)
open-on-github, v1.2.1 (inactive)
package-generator, v1.0.1 (inactive)
settings-view, v0.243.1 (active)
snippets, v1.0.4 (active)
spell-check, v0.68.4 (active)
status-bar, v1.4.1 (active)
styleguide, v0.47.2 (active)
symbols-view, v0.113.1 (inactive)
tabs, v0.103.0 (active)
timecop, v0.33.2 (active)
tree-view, v0.210.0 (active)
update-package-dependencies, v0.10.0 (active)
welcome, v0.35.1 (active)
whitespace, v0.35.0 (active)
wrap-guide, v0.38.2 (active)
language-c, v0.54.0 (active)
language-clojure, v0.22.1 (active)
language-coffee-script, v0.48.0 (active)
language-csharp, v0.13.0 (active)
language-css, v0.40.1 (active)
language-gfm, v0.88.0 (active)
language-git, v0.15.0 (active)
language-go, v0.43.0 (active)
language-html, v0.47.1 (active)
language-hyperlink, v0.16.1 (active)
language-java, v0.24.0 (active)
language-javascript, v0.122.0 (active)
language-json, v0.18.3 (active)
language-less, v0.29.6 (active)
language-make, v0.22.2 (active)
language-mustache, v0.13.0 (active)
language-objective-c, v0.15.1 (active)
language-perl, v0.37.0 (active)
language-php, v0.37.3 (active)
language-property-list, v0.8.0 (active)
language-python, v0.45.1 (active)
language-ruby, v0.70.2 (active)
language-ruby-on-rails, v0.25.1 (active)
language-sass, v0.57.0 (active)
language-shellscript, v0.23.0 (active)
language-source, v0.9.0 (active)
language-sql, v0.25.0 (active)
language-text, v0.7.1 (active)
language-todo, v0.29.1 (active)
language-toml, v0.18.1 (active)
language-xml, v0.34.12 (active)
language-yaml, v0.27.1 (active)

# Dev
No dev packages
```

**Comment by tuomashatakka** [comment] 2017-01-07 01:29
I'll fix that asap, there is an error which causes the variables for custom colors to have a value of false in a generated less file. This is caused by a check I originally added to prevent errors in the less output 😅 I've actually fixed this one already, just haven't had a chance yet to push the fixes. 

Thanks for the swift feedback and sorry for possible inconvenience.

**Comment by alanzanattadev** [comment] 2017-01-08 10:26
It doesn't crash anymore, that's a good point :D now fonts are too small on my screen, except the one of input field of command palette which is too big. General layout has weird metrics, I think it doesn't match what you've got on your screen.

Happy to help :) Every UI theme except One Dark are little bit ugly, so if I can help a good one to become great that's cool :) Cool animation on package hovering btw

**Comment by tuomashatakka** [comment] 2017-01-08 16:47
Yeah, the base font size used for scaling might be a bit small for the 4K resolution, I'll take a look at that. I generally use a display smaller than 1920x1080 so it's sometimes hard to remember to take the biggest resolutions into account.

Could you tell a bit more about which metrics you find weird? It shouldn't be too hard to change the overall, spacing since almost everything is dynamically sized. 

It's a shame Atom's base styles are so cluttered, it makes implementing anything non trivial really hard (not an issue any more though since I've managed to override the base styling almost entirely). But thanks again for the feedback. 

ps. if you feel like contributing to the theme at any point, it would be a blast! If you haven't contributed to others' projects before, I'd bee more than happy to get you started. It's not too hard if one has a basic knowledge of git's capabilities 🙋

**Comment by alanzanattadev** [comment] 2017-01-16 11:15
Sorry, I was busy :)

I'm the creator of many atom plugins :D http://atom.io/users/alanzanattadev :) But I don't have a lot of time to contribute to this one unfortunatly, can only send you issues

**Comment by tuomashatakka** [comment] 2017-01-16 14:01
Oh cool! I was afraid you had disappeared for good :D 

The docker plugin has caught my eye every time I've browsed plugins but never actually installed it, I guess I'll have to give it a try now! 

And the feedback from you has been more than useful, thanks again! (the font size changes are coming as soon as I'll finish the font selection :)) 

ps. do you happen to have any tips or such for interacting with the settings view package? I have been desperately trying to find any interface to edit the theme's settings ever since I started this project, but it seems like every path is dead end. Yesterday i discovered the activation callback object from settings view's space pen; but I still need to observe for pane changes to be able to update the activation callback. Is it really impossible to create a new input type without any dirty solutions... :0

**Comment by alanzanattadev** [comment] 2017-01-16 15:00
Atom lives on a weird base with Space Pen, it tends to evolve but I don't interact with those kind of hacked things ;)

**Comment by alanzanattadev** [comment] 2017-01-17 00:28
Begins to look good, even on my xps :D Some font size (package name in settings, and input field of command palette) are really really big.

**Comment by tuomashatakka** [comment] 2017-01-19 03:23
Scaling added to the settings, I'll close this for now

**Closed by tuomashatakka** 2017-01-19 03:23 UTC
